feat: added docker build step

diff --git a/.github/workflows/build-dist-version-on-release.yaml b/.github/workflows/build-dist-version-on-release.yaml
--- a/.github/workflows/build-dist-version-on-release.yaml
+++ b/.github/workflows/build-dist-version-on-release.yaml
@@ -22,3 +22,37 @@ jobs:
         with:
           name: dist-${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
           path: build
+
+  build-distribution-version-into-docker-container:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        name: Checkout repository
+
+      - name: Check if secrets exist
+        run: |
+          if [[ -z "${{ secrets.DOCKER_LOGIN_SERVER }}" || -z "${{ secrets.DOCKER_USERNAME }}" || -z "${{ secrets.DOCKER_PASSWORD }}" ]]; then
+            echo "Error: Secrets not found."
+            exit 1
+          fi
+
+      - uses: docker/login-action@v2
+        name: Log in to the Container registry
+        with:
+          registry: ${{ secrets.DOCKER_LOGIN_SERVER}}
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - uses: docker/setup-buildx-action@v2
+        name: Set up Docker Buildx
+        id: buildx
+
+      - uses: docker/build-push-action@v4
+        name: Build and push Docker image
+        with:
+          context: .
+          file: Dockerfile
+          cache-from: type=registry,ref=${{ secrets.DOCKER_LOGIN_SERVER }}/${{ github.event.repository.name }}:cache
+          cache-to: type=registry,ref=${{ secrets.DOCKER_LOGIN_SERVER }}/${{ github.event.repository.name }}:cache,mode=max
+          push: true
+          tags: ${{ secrets.DOCKER_LOGIN_SERVER }}/${{ github.event.repository.name }}${{ github.event.release.tag_name }}
